baseURL = "https://reyste.com/"
canonifyURLs = true
copyright = "Steve Beyer"
defaultContentLanguage = "en"
enableGitInfo = true
showReadingTime = true
title = "Steve Beyer"

disableKinds = ["section"]

[Taxonomies]
categories = "categories"

[languages]

[languages.en]
languageName = "English"
weight = 1.0

# [languages.de]
# languageName = "Deutsch"
# weight = 2.0

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "native"
