baseURL = "https://stvbyr.tech/"
canonifyURLs = true
copyright = "Steve Beyer"
defaultContentLanguage = "en"
enableGitInfo = true
showReadingTime = true
title = "stvbyr.tech"
enableRobotsTXT = true

disableKinds = ["section"]

[Taxonomies]
categories = "categories"

[languages]

[languages.en]
languageName = "English"
weight = 1.0

# [languages.de]
# languageName = "Deutsch"
# weight = 2.0

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "rrt"
tabWidth = 2
lineNos = true
noclasses = false

[Params]

[Params.seo.twitter]
handle = "stvbyr"

[Params.brand]
logo_500px = "apple-icon-180x180.png"

[Params.meta]
author = "Steve Beyer"
description = "My name is Steve Beyer. This blog is about tech related articles mostly php, software design and personal growth."

[Params.social]

[Params.social.profiles]
twitter = "https://twitter.com/stvbyr"
github = "https://github.com/stvbyr"

[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "Linear"
