#basic
baseURL: https://steve-beyer.com/
title: Steve Beyer

# lang
defaultContentLanguage: en
languages:
    en:
        languageName: English
        weight: 1
        taxonomies:
            categories: categories
    de:
        languageName: Deutsch
        weight: 2
        taxonomies:
            categories: Kategorien

# misc
enableGitInfo: true
showReadingTime: true
canonifyURLs: true
copyright: Steve Beyer
summaryLength: 20

markup:
  goldmark:
    renderer:
      unsafe: true
