#basic
baseURL: http://yerstem.com/
title: Yerstem

# lang
defaultContentLanguage: en
languages:
  en:
    languageName: English
    weight: 1
  de:
    languageName: Deutsch
    weight: 2

# misc
enableGitInfo: true
