baseURL = "https://steve-beyer.com/"
canonifyURLs = true
copyright = "Steve Beyer"
defaultContentLanguage = "en"
enableGitInfo = true
showReadingTime = true
title = "Steve Beyer"

[languages]

[languages.en]
languageName = "English"
weight = 1.0

[languages.en.taxonomies]
categories = "categories"

[languages.de]
languageName = "Deutsch"
weight = 2.0

[languages.de.taxonomies]
categories = "Kategorien"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "native"
