#basic
baseURL: https://yerstem.com/
title: Yerstem

# lang
defaultContentLanguage: en
languages:
    en:
        languageName: English
        weight: 1
        taxonomies:
            categories: categories
    de:
        languageName: Deutsch
        weight: 2
        taxonomies:
            categories: Kategorien

# misc
enableGitInfo: true
showReadingTime: true
canonifyURLs: true
copyright: Steve Beyer
summaryLength: 30

params:
    meta:
        tagline: "Coding and more"

markup:
  goldmark:
    renderer:
      unsafe: true
