services:
    server:
        container_name: hugo_server
        build:
            dockerfile: ./Dockerfile
            context: .
            args:
                NODE_VERSION: "18.16.1"
                GO_VERSION: "1.20"
                HUGO_VERSION: "0.114.1"
        volumes:
            - .:/homes/node/stvbyr-tech
            - /homes/node/stvbyr-tech/node_modules
        ports:
            - 1313:1313

