services:
    server:
        container_name: hugo_server
        build:
            dockerfile: ./build/Dockerfile
            context: .
            args:
                NODE_VERSION: 16.14.0
                GO_VERSION: 1.19
                HUGO_VERSION: 'v0.101.0'
        volumes:
            - .:/src/stvbyr-tech
        ports:
            - 1313:1313

